#!/usr/bin/env python3
"""
CyberCypher Mainframe Core Expansion Pipeline
Optimized Build Script: Injects 26 unique minified cyberpunk UI assets.
Path: C:\\Users\\qamel\\Downloads\\N8DEV\\CyberCypher\\index.html
"""

import os
import shutil
from bs4 import BeautifulSoup

TARGET_PATH = r"C:\Users\qamel\Downloads\N8DEV\CyberCypher\index.html"
BACKUP_PATH = TARGET_PATH + ".bak"

# 26 High-Performance Cyberpunk Assets (Minified for maximum efficiency without functional loss)
ASSETS_DATA = [
    # --- ORIGINAL 6 ARCHETYPES ---
    """<div class="cyber-asset-card" data-category="loaders" data-fps="60 FPS [ULTRA]" data-compile="0.01 ms" data-weight="0.4KB"><div class="asset-header"><span class="asset-tag">LOADERS // SYS</span><h3>Progress Bar</h3><p>Stream loader with neon scanning line matrix.</p></div><div class="asset-preview-box"><div class="cy-pb-w"><div class="cy-pb-b" style="width:75%"><div class="cy-pb-s"></div></div><span class="cy-pb-r">75% // LOAD</span></div></div><style>.cy-pb-w{width:100%;max-width:300px;background:rgba(0,243,255,.05);border:1px solid rgba(0,243,255,.2);padding:4px;font-family:monospace}.cy-pb-b{height:16px;background:#00F3FF;box-shadow:0 0 8px #00F3FF;position:relative;overflow:hidden}.cy-pb-s{width:100%;height:100%;background:linear-gradient(90deg,transparent,rgba(255,255,255,.4),transparent);transform:translateX(-100%);animation:cy-sc 1.5s infinite linear}.cy-pb-r{display:block;text-align:right;font-size:9px;color:#00F3FF;margin-top:3px}@keyframes cy-sc{100%{transform:translateX(100%)}}</style></div>""",
    """<div class="cyber-asset-card" data-category="inputs" data-fps="90 FPS [EXTREME]" data-compile="0.02 ms" data-weight="0.3KB"><div class="asset-header"><span class="asset-tag">INPUTS // UI</span><h3>Toggle Switch</h3><p>Binary matrix flip state mechanism.</p></div><div class="asset-preview-box"><label class="cy-sw-l"><input type="checkbox" class="cy-sw-i" checked><span class="cy-sw-c"></span><span class="cy-sw-t">SYS_STATUS</span></label></div><style>.cy-sw-l{display:inline-flex;align-items:center;cursor:pointer;font-family:monospace;color:#fff}.cy-sw-i{display:none}.cy-sw-c{width:44px;height:20px;border:2px solid #FF007F;background:rgba(255,0,127,.1);position:relative;margin-right:10px}.cy-sw-c::before{content:'';position:absolute;width:12px;height:12px;top:2px;left:2px;background:#FF007F;transition:.2s}.cy-sw-i:checked+.cy-sw-c{border-color:#39FF14;background:rgba(57,255,20,.1)}.cy-sw-i:checked+.cy-sw-c::before{background:#39FF14;left:26px;box-shadow:0 0 8px #39FF14}.cy-sw-t{font-size:11px}</style></div>""",
    """<div class="cyber-asset-card" data-category="interactive" data-fps="60 FPS [ULTRA]" data-compile="0.05 ms" data-weight="0.5KB"><div class="asset-header"><span class="asset-tag">ALERT // NET</span><h3>Notification Toast</h3><p>RGB split glitch entry warning module.</p></div><div class="asset-preview-box"><div class="cy-ts alert-state"><div class="cy-ts-i"><span>⚠️</span><div><span class="cy-ts-tl">FIREWALL_BREACH</span><span class="cy-ts-ds">Payload trace at segment 0x4F7E.</span></div></div></div></div><style>.cy-ts{background:#111;border-left:4px solid #FF007F;padding:10px;max-width:280px;font-family:monospace;color:#fff;animation:cy-gt .4s ease-out}.cy-ts-i{display:flex;align-items:center;gap:10px;font-size:11px}.cy-ts-tl{display:block;font-weight:700;color:#FF007F}.cy-ts-ds{display:block;font-size:9px;color:#ccc}@keyframes cy-gt{0%{transform:translateX(-10px);clip-path:inset(40% 0 30% 0)}20%{transform:translateX(5px);clip-path:inset(10% 0 70% 0)}100%{transform:translateX(0);clip-path:inset(0 0 0 0)}}</style></div>""",
    """<div class="cyber-asset-card" data-category="interactive" data-fps="90 FPS [EXTREME]" data-compile="0.03 ms" data-weight="0.4KB"><div class="asset-header"><span class="asset-tag">NAV // NODE</span><h3>Floating Menu</h3><p>Futuristic micro-navigation deck array.</p></div><div class="asset-preview-box"><div class="cy-fm"><button class="cy-fm-n active">[&gt;]</button><button class="cy-fm-n">[#]</button><button class="cy-fm-n">[*]</button></div></div><style>.cy-fm{display:inline-flex;gap:5px;background:rgba(0,0,0,.8);border:1px solid #00F3FF;padding:4px}.cy-fm-n{background:transparent;border:1px solid transparent;color:#00F3FF;width:30px;height:30px;cursor:pointer;font-family:monospace;font-weight:700;font-size:11px;transition:.15s}.cy-fm-n:hover,.cy-fm-n.active{background:#00F3FF;color:#111;box-shadow:0 0 8px #00F3FF}</style></div>""",
    """<div class="cyber-asset-card" data-category="cards" data-fps="60 FPS [ULTRA]" data-compile="0.08 ms" data-weight="0.5KB"><div class="asset-header"><span class="asset-tag">DATA // CORE</span><h3>Telemetry Widget</h3><p>Mainframe network grid performance visualizer.</p></div><div class="asset-preview-box"><div class="cy-tm"><div class="cy-tm-h">NET_LOAD // FREQ_A</div><div class="cy-tm-g"><div class="cy-tm-b" style="height:40%"></div><div class="cy-tm-b" style="height:85%"></div><div class="cy-tm-b" style="height:60%"></div><div class="cy-tm-b" style="height:95%"></div></div></div></div><style>.cy-tm{width:180px;background:#0b0b0e;border:1px solid rgba(57,255,20,.2);padding:8px;font-family:monospace}.cy-tm-h{color:#39FF14;font-size:9px;margin-bottom:6px}.cy-tm-g{display:flex;align-items:flex-end;justify-content:space-between;height:40px;background:rgba(0,0,0,.3);padding:2px}.cy-tm-b{width:18px;background:linear-gradient(to top,rgba(57,255,20,.2),#39FF14);box-shadow:0 0 4px #39FF14}</style></div>""",
    """<div class="cyber-asset-card" data-category="interactive" data-fps="120 FPS [MAX]" data-compile="0.01 ms" data-weight="0.2KB"><div class="asset-header"><span class="asset-tag">UI // HINT</span><h3>Tech Tooltip</h3><p>Instant hardware acceleration overlay parameter.</p></div><div class="asset-preview-box"><div class="cy-tt">[HOVER_NODE]<div class="cy-tt-c"><div class="cy-tt-m">ID: 99x</div>Matrix active.</div></div></div><style>.cy-tt{position:relative;display:inline-block;padding:4px 8px;background:#1a1a1f;color:#00F3FF;border:1px dashed #00F3FF;font-family:monospace;font-size:10px;cursor:help}.cy-tt-c{position:absolute;bottom:125%;left:50%;transform:translateX(-50%);background:#00F3FF;color:#000;padding:6px;width:110px;opacity:0;transition:.15s;pointer-events:none;clip-path:polygon(0 0,90% 0,100% 30%,100% 100%,0 100%)}.cy-tt-m{font-size:8px;text-decoration:underline}.cy-tt:hover .cy-tt-c{opacity:1}</style></div>""",

    # --- 20 ADDITIONALLY SYNTHESIZED ADVANCED COMPONENT VARIANTS ---
    """<div class="cyber-asset-card" data-category="buttons" data-fps="120 FPS" data-compile="0.01ms" data-weight="0.2KB"><div class="asset-header"><h3>Glitch Trigger</h3></div><button class="b-gl" onclick="alert('SYS_INIT')">RUN_CMD</button><style>.b-gl{background:#111;color:#39FF14;border:1px solid #39FF14;padding:6px 12px;font-family:monospace;cursor:pointer;position:relative}.b-gl:hover{text-shadow:-2px 0 #ff007f,2px 0 #00f3ff;box-shadow:0 0 8px #39FF14}</style></div>""",
    """<div class="cyber-asset-card" data-category="buttons" data-fps="90 FPS" data-compile="0.02ms" data-weight="0.3KB"><div class="asset-header"><h3>Secure Wipe</h3></div><button class="b-wp" onmousedown="t=toggle=setTimeout(()=>alert('PURGED'),1000)" onmouseup="clearTimeout(t)">HOLD_TO_PURGE</button><style>.b-wp{background:rgba(255,0,127,.1);color:#FF007F;border:2px solid #FF007F;padding:8px;font-family:monospace;cursor:pointer;transition:.1s}.b-wp:active{background:#FF007F;color:#000;box-shadow:0 0 15px #FF007F}</style></div>""",
    """<div class="cyber-asset-card" data-category="buttons" data-fps="144 FPS" data-compile="0.01ms" data-weight="0.2KB"><div class="asset-header"><h3>Hex Deploy</h3></div><div class="hx-d" onclick="this.classList.toggle('ac')">HEX</div><style>.hx-d{width:50px;height:28px;background:#222;color:#00F3FF;display:flex;align-items:center;justify-content:center;font-family:monospace;clip-path:polygon(25% 0%,75% 0%,100% 50%,75% 100%,25% 100%,0% 50%);cursor:pointer}.hx-d.ac{background:#00F3FF;color:#000;box-shadow:0 0 10px #00F3FF}</style></div>""",
    """<div class="cyber-asset-card" data-category="buttons" data-fps="60 FPS" data-compile="0.02ms" data-weight="0.3KB"><div class="asset-header"><h3>Scan Trigger</h3></div><button class="b-sc">SCAN_NET<div class="sc-l"></div></button><style>.b-sc{background:#000;color:#00F3FF;border:1px solid #00F3FF;padding:6px;position:relative;overflow:hidden;cursor:pointer;font-family:monospace}.sc-l{position:absolute;top:0;left:0;width:100%;height:2px;background:#00F3FF;animation:sc-an 1s infinite}</style></div>""",
    """<div class="cyber-asset-card" data-category="loaders" data-fps="60 FPS" data-compile="0.03ms" data-weight="0.2KB"><div class="asset-header"><h3>Radar Sync</h3></div><div class="rd-l"></div><style>.rd-l{width:30px;height:30px;border:2px solid transparent;border-top-color:#39FF14;border-radius:50%;animation:rd-spin 1s infinite linear;margin:10px}@keyframes rd-spin{100%{transform:rotate(360deg)}}</style></div>""",
    """<div class="cyber-asset-card" data-category="loaders" data-fps="90 FPS" data-compile="0.01ms" data-weight="0.3KB"><div class="asset-header"><h3>Pulse Nodes</h3></div><div class="p-nd"><div class="nd"></div><div class="nd"></div><div class="nd"></div></div><style>.p-nd{display:flex;gap:5px;padding:10px}.nd{width:6px;height:6px;background:#FF007F;animation:nd-p .6s infinite alternate}.nd:nth-child(2){animation-delay:.2s}.nd:nth-child(3){animation-delay:.4s}@keyframes nd-p{100%{transform:scale(1.8);opacity:.3}}</style></div>""",
    """<div class="cyber-asset-card" data-category="loaders" data-fps="60 FPS" data-compile="0.02ms" data-weight="0.4KB"><div class="asset-header"><h3>Matrix Terminal</h3></div><div class="mx-t" id="mx-txt"></div><script>setInterval(()=>{document.getElementById('mx-txt').innerText=Math.random().toString(2).substr(2,8)},200)</script><style>.mx-t{font-family:monospace;color:#39FF14;font-size:12px;letter-spacing:2px;min-height:18px}</style></div>""",
    """<div class="cyber-asset-card" data-category="loaders" data-fps="75 FPS" data-compile="0.04ms" data-weight="0.5KB"><div class="asset-header"><h3>Block Fall</h3></div><div class="bk-f"><div class="bk"></div><div class="bk"></div></div><style>.bk-f{display:flex;gap:3px;height:20px}.bk{width:10px;height:100%;background:#00F3FF;animation:bk-a 1s infinite ease-in-out alternate}.bk:nth-child(2){animation-delay:.5s}@keyframes bk-a{0%{height:20%}100%{height:100%}}</style></div>""",
    """<div class="cyber-asset-card" data-category="inputs" data-fps="120 FPS" data-compile="0.01ms" data-weight="0.3KB"><div class="asset-header"><h3>Secure Key</h3></div><input type="password" class="in-s" placeholder="PASSKEY"><style>.in-s{background:#111;border:1px solid #FF007F;color:#FF007F;padding:4px;font-family:monospace;outline:none;font-size:11px}.in-s:focus{box-shadow:0 0 8px #FF007F}</style></div>""",
    """<div class="cyber-asset-card" data-category="inputs" data-fps="90 FPS" data-compile="0.02ms" data-weight="0.2KB"><div class="asset-header"><h3>Cyber Range</h3></div><input type="range" class="rn-c"><style>.rn-c{-webkit-appearance:none;background:#222;height:4px}.rn-c::-webkit-slider-thumb{-webkit-appearance:none;width:12px;height:12px;background:#00F3FF;cursor:pointer;border-radius:0}</style></div>""",
    """<div class="cyber-asset-card" data-category="inputs" data-fps="90 FPS" data-compile="0.01ms" data-weight="0.3KB"><div class="asset-header"><h3>Radio Pill</h3></div><label class="rd-p"><input type="radio" name="cyber-r" class="rd-i" checked><span>NODE_01</span></label><style>.rd-p{font-family:monospace;color:#39FF14;cursor:pointer}.rd-i{-webkit-appearance:none;width:10px;height:10px;border:1px solid #39FF14;margin-right:5px;display:inline-block}.rd-i:checked{background:#39FF14}</style></div>""",
    """<div class="cyber-asset-card" data-category="inputs" data-fps="60 FPS" data-compile="0.03ms" data-weight="0.5KB"><div class="asset-header"><h3>Matrix Select</h3></div><select class="sl-m"><option>V1.0</option><option>V2.0</option></select><style>.sl-m{background:#000;color:#00F3FF;border:1px solid #00F3FF;font-family:monospace;padding:2px}</style></div>""",
    """<div class="cyber-asset-card" data-category="cards" data-fps="90 FPS" data-compile="0.01ms" data-weight="0.3KB"><div class="asset-header"><h3>Border Frame</h3></div><div class="cd-b">CORE_READY</div><style>.cd-b{border:2px solid #00F3FF;padding:10px;background:rgba(0,243,255,.02);font-family:monospace;color:#fff;clip-path:polygon(0 0,85% 0,100% 25%,100% 100%,0 100%)}</style></div>""",
    """<div class="cyber-asset-card" data-category="cards" data-fps="60 FPS" data-compile="0.04ms" data-weight="0.4KB"><div class="asset-header"><h3>Warning Pod</h3></div><div class="cd-w">SYS_OVERHEAT</div><style>.cd-w{border:1px solid #FF007F;background:repeating-linear-gradient(45deg,transparent,transparent 10px,rgba(255,0,127,.05) 10px,rgba(255,0,127,.05) 20px);padding:12px;color:#FF007F;font-family:monospace;font-weight:700}</style></div>""",
    """<div class="cyber-asset-card" data-category="cards" data-fps="120 FPS" data-compile="0.02ms" data-weight="0.3KB"><div class="asset-header"><h3>Glow Stack</h3></div><div class="cd-g">DATA_STREAM</div><style>.cd-g{background:#111;padding:8px;color:#39FF14;font-family:monospace;box-shadow:inset 0 0 10px rgba(57,255,20,.3),0 0 10px rgba(57,255,20,.2)}</style></div>""",
    """<div class="cyber-asset-card" data-category="cards" data-fps="90 FPS" data-compile="0.02ms" data-weight="0.5KB"><div class="asset-header"><h3>Splice Card</h3></div><div class="cd-s"><div class="s-tp"></div>LINK_ESTABLISHED</div><style>.cd-s{position:relative;background:#15151c;border:1px solid #222;padding:12px;color:#fff;font-family:monospace}.s-tp{position:absolute;top:-1px;left:10px;width:30px;height:2px;background:#00F3FF}</style></div>""",
    """<div class="cyber-asset-card" data-category="interactive" data-fps="144 FPS" data-compile="0.01ms" data-weight="0.2KB"><div class="asset-header"><h3>Audio Node</h3></div><div class="av-n" onclick="this.classList.toggle('pl')"></div><style>.av-n{width:16px;height:16px;background:#39FF14;cursor:pointer;clip-path:polygon(0 0,100% 50%,0 100%)}.av-n.pl{clip-path:polygon(0 0,30% 0,30% 100%,0 100%,70% 0,100% 0,100% 100%,70% 100%)}</style></div>""",
    """<div class="cyber-asset-card" data-category="interactive" data-fps="120 FPS" data-compile="0.02ms" data-weight="0.4KB"><div class="asset-header"><h3>Tab Select</h3></div><div class="tb-s"><span class="ac">A1</span><span>A2</span></div><style>.tb-s{display:flex;background:#000;border:1px solid #FF007F;font-family:monospace}.tb-s span{padding:4px 8px;color:#FF007F;cursor:pointer}.tb-s span.ac{background:#FF007F;color:#000}</style></div>""",
    """<div class="cyber-asset-card" data-category="interactive" data-fps="90 FPS" data-compile="0.03ms" data-weight="0.3KB"><div class="asset-header"><h3>Close Node</h3></div><div class="cl-n" onclick="alert('CLOSE')">&times;</div><style>.cl-n{width:20px;height:20px;border:1px solid #FF007F;color:#FF007F;text-align:center;line-height:18px;font-family:monospace;cursor:pointer;transition:.2s}.cl-n:hover{background:#FF007F;color:#000}</style></div>""",
    """<div class="cyber-asset-card" data-category="interactive" data-fps="60 FPS" data-compile="0.05ms" data-weight="0.5KB"><div class="asset-header"><h3>Copier Tag</h3></div><div class="cp-t" onclick="navigator.clipboard.writeText('0x88F')">0x88F [COPY]</div><style>.cp-t{display:inline-block;padding:2px 6px;background:rgba(0,243,255,.1);border:1px solid #00F3FF;color:#00F3FF;font-family:monospace;font-size:10px;cursor:pointer}</style></div>"""
]

def compile_cyber_workspace():
    if not os.path.exists(TARGET_PATH):
        print(f"[ERROR] Target path invalid: {TARGET_PATH}")
        return

    # Create safety backup matrix
    shutil.copyfile(TARGET_PATH, BACKUP_PATH)
    print(f"[BACKUP COMPLETE] Rollback reference generated at: {BACKUP_PATH}")

    with open(TARGET_PATH, 'r', encoding='utf-8') as f:
        soup = BeautifulSoup(f.read(), 'html.parser')

    # Locate asset catalog deployment workspace layout framework
    container = (
        soup.find(class_='asset-catalog-layout') or
        soup.find(class_='assets-grid') or
        soup.find(id='assets-container') or
        soup.find(class_='sidebar') or
        soup.find('main') or
        soup.find('body')
    )

    print(f"[COMPILING] Target injection point isolated: <{container.name}>")

    # Dynamic parsing and asset rendering stream loop
    for asset_raw in ASSETS_DATA:
        asset_soup = BeautifulSoup(asset_raw, 'html.parser')
        container.append(asset_soup)

    # Output back to file using automated line compression layout rules
    with open(TARGET_PATH, 'w', encoding='utf-8') as f:
        f.write(str(soup))

    print(f"[DEPLOYMENT EXPANSION SUCCESSFUL] 26 high-performance minified items compiled cleanly to workspace.")

if __name__ == "__main__":
    compile_cyber_workspace()
